name: settings_api
description: An abstract class and models for an API providing access to settings.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.1.11
  coverage: ^1.5.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.16.0
