name: pln_converter
description: Polish zloty currency converter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  exchange_rates_repository:
    path: packages/exchange_rates_repository
  settings_repository:
    path: packages/settings_repository
  shared_preferences_settings_api:
    path: packages/shared_preferences_settings_api
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  coverage: ^1.3.2

flutter:
  uses-material-design: true
