name: exchange_rates_repository
description: A repository that handles exchange rates requests.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  equatable: ^2.0.3
  nbp_api:
    path: ../nbp_api

dev_dependencies:
  coverage: ^1.5.0
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
