name: shared_preferences_settings_api
description: An implementation of the SettingsApi that uses shared preferences plugin.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  settings_api:
    path: ../settings_api
  shared_preferences: ^2.0.15

dev_dependencies:
  coverage: ^1.5.0
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
