name: shared_preferences_settings_api
description: A Flutter implementation of the SettingsApi that uses shared preferences.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  settings_api:
    path: ../settings_api
  shared_preferences: ^2.0.15

dev_dependencies:
  coverage: ^1.3.2
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  mocktail: ^0.3.0
