name: nbp_api_test
on:
  pull_request:
    branches:
      - master
  # push:
  #   paths:
  #     - "packages/nbp_api/**"
  #     - ".github/workflows/nbp_api.yaml"
  # pull_request:
  #   paths:
  #     - "packages/nbp_api/**"
  #     - ".github/workflows/nbp_api.yaml"

jobs:
  flutter_test:
    defaults:
      run:
        working-directory: packages/nbp_api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test --coverage
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: nbp_api
