name: settings_repository
on:
  push:
    paths:
      - ".github/workflows/settings_repository.yaml"
      - "packages/settings_repository/**"
  pull_request:
    paths:
      - ".github/workflows/settings_repository.yaml"
      - "packages/settings_repository/**"

jobs:
  flutter_test:
    defaults:
      run:
        working-directory: packages/settings_repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test --coverage
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: settings_repository
