name: shared_preferences_settings_api
on:
  push:
    paths:
      - ".github/workflows/shared_preferences_settings_api.yaml"
      - "packages/shared_preferences_settings_api/**"

jobs:
  flutter_test:
    defaults:
      run:
        working-directory: packages/shared_preferences_settings_api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test --coverage
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: shared_preferences_settings_api
